import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

const nunitoSans = Nunito_Sans({
	weight: ["400", "500", "600", "700"],
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Whisper Notes",
	description: "Generated by create next app",
	icons: {
		icon: "./favicon.ico",
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={nunitoSans.className}>
			<body className="bg-gray-900">
				<Toaster richColors />
				{children}
			</body>
		</html>
	);
}
